package com.actively.ui.theme

import androidx.compose.ui.graphics.Color

object LightColors {

    val primary = Color(0xFF7E5700)
    val onPrimary = Color(0xFFFFFFFF)
    val primaryContainer = Color(0xFFFFDEAB)
    val onPrimaryContainer = Color(0xFF271900)
    val secondary = Color(0xFF6D5C3F)
    val onSecondary = Color(0xFFFFFFFF)
    val secondaryContainer = Color(0xFFF8DFBB)
    val onSecondaryContainer = Color(0xFF261904)
    val tertiary = Color(0xFF4E6543)
    val onTertiary = Color(0xFFFFFFFF)
    val tertiaryContainer = Color(0xFFD0EAC0)
    val onTertiaryContainer = Color(0xFF0C2006)
    val error = Color(0xFFBA1A1A)
    val errorContainer = Color(0xFFFFDAD6)
    val onError = Color(0xFFFFFFFF)
    val onErrorContainer = Color(0xFF410002)
    val background = Color(0xFFFFFBFF)
    val onBackground = Color(0xFF1F1B16)
    val surface = Color(0xFFFFFBFF)
    val onSurface = Color(0xFF1F1B16)
    val surfaceVariant = Color(0xFFEEE0CF)
    val onSurfaceVariant = Color(0xFF4E4539)
    val outline = Color(0xFF807667)
    val inverseOnSurface = Color(0xFFF8EFE7)
    val inverseSurface = Color(0xFF34302A)
    val inversePrimary = Color(0xFFFABC49)
    val shadow = Color(0xFF000000)
    val surfaceTint = Color(0xFF7E5700)
    val outlineVariant = Color(0xFFD2C5B4)
    val scrim = Color(0xFF000000)
}

object DarkColors {

    val primary = Color(0xFFFABC49)
    val onPrimary = Color(0xFF422C00)
    val primaryContainer = Color(0xFF5F4100)
    val onPrimaryContainer = Color(0xFFFFDEAB)
    val secondary = Color(0xFFDBC3A1)
    val onSecondary = Color(0xFF3C2E16)
    val secondaryContainer = Color(0xFF54442A)
    val onSecondaryContainer = Color(0xFFF8DFBB)
    val tertiary = Color(0xFFB4CEA5)
    val onTertiary = Color(0xFF213618)
    val tertiaryContainer = Color(0xFF374D2D)
    val onTertiaryContainer = Color(0xFFD0EAC0)
    val error = Color(0xFFFFB4AB)
    val errorContainer = Color(0xFF93000A)
    val onError = Color(0xFF690005)
    val onErrorContainer = Color(0xFFFFDAD6)
    val background = Color(0xFF1F1B16)
    val onBackground = Color(0xFFEAE1D9)
    val surface = Color(0xFF1F1B16)
    val onSurface = Color(0xFFEAE1D9)
    val surfaceVariant = Color(0xFF4E4539)
    val onSurfaceVariant = Color(0xFFD2C5B4)
    val outline = Color(0xFF9A8F80)
    val inverseOnSurface = Color(0xFF1F1B16)
    val inverseSurface = Color(0xFFEAE1D9)
    val inversePrimary = Color(0xFF7E5700)
    val shadow = Color(0xFF000000)
    val surfaceTint = Color(0xFFFABC49)
    val outlineVariant = Color(0xFF4E4539)
    val scrim = Color(0xFF000000)
}

val seed = Color(0xFFFABC49)
